[package]
name = "app-gui"
version.workspace = true
edition.workspace = true

[dependencies]
app-common = { workspace = true }

eframe = { version = "0.32.0", features = ["default"] }
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
font-kit = "0.14.3"
memmap2 = "0.9.7"

[lints]
workspace = true

[[bin]]
name = "gameslauncher_rs_2_gui"
path = "src/main.rs"
